# -*- coding: utf-8 -*-
"""chatbhot

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WGXzoja92Id84_tdw_4ET43iaYgoN9Rx
"""

!pip install scikit-learn nltk

intents = {
    "intents": [
        {
            "tag": "greeting",
            "patterns": ["Hi", "Hello", "Hey", "Good day", "What's up?", "Howdy"],
            "responses": ["Hello!", "Hi there!", "Greetings!", "Hey! How can I help you?"]
        },
        {
            "tag": "goodbye",
            "patterns": ["Bye", "See you", "Goodbye", "Take care", "Catch you later"],
            "responses": ["Goodbye!", "See you later!", "Take care!", "Bye! Come back soon."]
        },
        {
            "tag": "thanks",
            "patterns": ["Thanks", "Thank you", "That's helpful", "Thanks a lot"],
            "responses": ["You're welcome!", "Glad to help!", "Anytime!", "No problem!"]
        },
        {
            "tag": "name",
            "patterns": ["What is your name?", "Who are you?", "Identify yourself", "What's your name?"],
            "responses": ["I'm your ML Chatbot!", "You can call me Chatbot.", "I'm a simple ML-powered assistant."]
        },
        {
            "tag": "weather",
            "patterns": ["How's the weather?", "Is it sunny?", "Will it rain today?", "Weather update"],
            "responses": ["I can't give real-time weather updates yet, but it's always sunny in here!"]
        },
        {
            "tag": "joke",
            "patterns": ["Tell me a joke", "Make me laugh", "Say something funny"],
            "responses": ["Why don’t scientists trust atoms? Because they make up everything!",
                          "I'm reading a book on anti-gravity. It’s impossible to put down!"]
        },
        {
            "tag": "help",
            "patterns": ["Can you help me?", "I need support", "Help me", "Assist me"],
            "responses": ["Of course! I'm here to help.", "Sure! What do you need assistance with?"]
        },
        {
            "tag": "age",
            "patterns": ["How old are you?", "What's your age?", "Since when do you exist?"],
            "responses": ["I'm timeless 😄", "I was born when you ran this notebook!"]
        }
    ]
}

import nltk
nltk.download('punkt')
nltk.download('averaged_perceptron_tagger')

import random
import nltk
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.pipeline import make_pipeline

# Download NLTK data
nltk.download('punkt')

# Prepare data
X = []
y = []

for intent in intents['intents']:
    for pattern in intent['patterns']:
        X.append(pattern)
        y.append(intent['tag'])

# Train model
model = make_pipeline(CountVectorizer(), MultinomialNB())
model.fit(X, y)

# Chat function
def chatbot_response(user_input):
    tag = model.predict([user_input])[0]
    for intent in intents['intents']:
        if intent['tag'] == tag:
            return random.choice(intent['responses'])

# Simple chat loop in Colab
while True:
    inp = input("You: ")
    if inp.lower() == 'quit':
        print("Bot: Goodbye!")
        break
    response = chatbot_response(inp)
    print("Bot:", response)